export const INITIAL_STATE = 'INITIAL_STATE';
export const FETCH_WEATHER_FORECAST_BEGIN = 'FETCH_WEATHER_FORECAST_BEGIN';
export const FETCH_WEATHER_FORECAST_SUCCESS = 'FETCH_WEATHER_FORECAST_SUCCESS';
export const FETCH_WEATHER_FORECAST_FAILURE = 'FETCH_WEATHER_FORECAST_FAILURE';
